### PR TITLE
Fix `addLabels` having no effect for progressBar

### LINKED ISSUE #472: `addLabels` is ignored by the ProgressBar
### Please fill out these Check-boxes

- [X] I checked for existing similar issues
- [X] I checked that the plugin is up to date
- [X] The issue persists with all other plugins and themes disabled

### Plugin Version

1.2.5

### This Issue Occurs on

- [X] Windows
- [ ] Linux
- [ ] macOS
- [ ] Android
- [ ] iOS

### Debug Info

```text
SYSTEM INFO:
	Obsidian version: v1.7.7
	Installer version: v1.7.7
	Operating system: Windows 10 Enterprise 10.0.19045
	Login status: not logged in
	Language: en
	Insider build toggle: off
	Live preview: on
	Base theme: adapt to system
	Community theme: none
	Snippets enabled: 1
	Restricted mode: off
	Plugins installed: 2
	Plugins enabled: 2
		1: Meta Bind v1.2.5
		2: JS Engine v0.1.20

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.
```

### Describe the Issue

Using the `addLabels` porpertie on a `progressBar` input has no effect. 

### Steps to Reproduce

<pre><code>
```meta-bind
INPUT[progressBar(addLabels(true))]
```
```meta-bind
INPUT[progressBar(addLabels(false))]
```
</code></pre>

Both produce the exact same result.

### Expected Behavior

As documentded, using `addLabels(false)` should hide the labels.

### Additional Info

The option is loaded into the swelt-component same as in the slider, it's just never used:

https://github.com/mProjectsCode/obsidian-meta-bind-plugin/blob/09d63717c11b7ee455b636cf888445305fa33a3f/packages/core/src/fields/inputFields/fields/ProgressBar/ProgressBarComponent.svelte#L9

I am happy to provide a PR for this, I am just not sure if all three labels should be hidden or just the left and right one (leaving the current value displayed)

https://github.com/mProjectsCode/obsidian-meta-bind-plugin/blob/09d63717c11b7ee455b636cf888445305fa33a3f/packages/core/src/fields/inputFields/fields/ProgressBar/ProgressBarComponent.svelte#L130-L132

https://github.com/mProjectsCode/obsidian-meta-bind-plugin/blob/09d63717c11b7ee455b636cf888445305fa33a3f/packages/core/src/fields/inputFields/fields/Slider/SliderComponent.svelte#L31-L33

### PR DESCRIPTION
**Pull request by Cube707**
I implemented the fix, but am unsure if all three lables should be hidden or if the center one should be left 

closes #472

### CODE REVIEW

**Comment by mProjectsCode** [comment]
Not sure. I would say no, as otherwise there is no way of knowing what the value of the progress bar is when the labels are hidden.

**Comment by Cube707** [comment]
> Not sure. I would say no, as otherwise there is no way of knowing what the value of the progress bar is when the labels are hidden

I was thinking, that maybe one explicitly only want the visual feedback while handling the numeric values separately via a textbox? 

The slider also has only the visual feedback with labels of, so it might be more consistent?

**Comment by mProjectsCode** [comment]
Fair. I think no labels at all are fine.

**Comment by mProjectsCode** [comment]
Maybe a tooltip on hover is a good idea though.

File: packages/core/src/fields/inputFields/fields/ProgressBar/ProgressBarComponent.svelte [hunk 1]
```diff
@@ -125,9 +125,12 @@
 		aria-valuemin={props.minValue}
 		aria-valuemax={props.maxValue}
 		aria-valuenow={value}
+		aria-label={value}
```
Comment (Cube707) [inline packages/core/src/fields/inputFields/fields/ProgressBar/ProgressBarComponent.svelte:128]: I experimented a bit with with switching to `aria-labeledby` in case the labels are shown, but could get it to work. also this required a unique ID on the `mb-progress-bar-value` which adds unnecessary overhead

**Comment by mProjectsCode** [comment]
thanks
